### ISSUE TITLE
Incorporate Wycheproof

### ISSUE THREAD

**Issue by paulmillr** [get-smooth/crypto-lib#19]
Wycheproof vectors are a good source of edge cases. Take a glance at [noble-curves tests](https://github.com/paulmillr/noble-curves) for inspiration.

**Comment by rdubois-crypto** [comment]
Hi Paul. I am a big fan of noble-curves, and i am actually building stuffs using it for the front (wallet) side :)
I would gladly have private discussions with you (see my profile). 

SCL actually incorporate wycheproof vectors for secp256r1 :
https://github.com/get-smooth/crypto-lib/blob/main/test/vectors_wycheproof.jsonl

You might be referring to ed25519, for which only the vectors link to the rfc are provided. It shall be a good idea, actually Veridise our auditors told that they ran them, but i didn't checked.

**Comment by rdubois-crypto** [comment]
close with previous comment
